export {
  Pagination,
  PaginationControls,
  PaginationInfo,
  PaginationPageSize,
  PaginationSeparator,
  paginationVariants,
  KUMO_PAGINATION_DEFAULT_VARIANTS,
  KUMO_PAGINATION_VARIANTS,
  type KumoPaginationControls,
  type KumoPaginationVariantsProps,
  type PaginationCompoundProps,
  type PaginationControlsProps,
  type PaginationInfoProps,
  type PaginationInfoRenderProps,
  type PaginationLabels,
  type PaginationLegacyProps,
  type PaginationPageSizeProps,
  type PaginationProps,
  type PaginationSeparatorProps,
} from "./pagination";
