/**
 * SSR-safe Solid wrappers around the official Phosphor SVG assets.
 *
 * Generated by scripts/generate-solid-icons.mjs. The adapter intentionally
 * mirrors the React package's component names so docs markup can migrate
 * without changing icon geometry, weights, or sizing.
 */
import { splitProps, type Component, type JSX } from "solid-js";

import ArrowLeftSvgBold from "@phosphor-icons/core/bold/arrow-left-bold.svg?raw";
import ArrowLeftSvgDuotone from "@phosphor-icons/core/duotone/arrow-left-duotone.svg?raw";
import ArrowLeftSvgFill from "@phosphor-icons/core/fill/arrow-left-fill.svg?raw";
import ArrowLeftSvgLight from "@phosphor-icons/core/light/arrow-left-light.svg?raw";
import ArrowLeftSvgRegular from "@phosphor-icons/core/regular/arrow-left.svg?raw";
import ArrowLeftSvgThin from "@phosphor-icons/core/thin/arrow-left-thin.svg?raw";
import ArrowRightSvgBold from "@phosphor-icons/core/bold/arrow-right-bold.svg?raw";
import ArrowRightSvgDuotone from "@phosphor-icons/core/duotone/arrow-right-duotone.svg?raw";
import ArrowRightSvgFill from "@phosphor-icons/core/fill/arrow-right-fill.svg?raw";
import ArrowRightSvgLight from "@phosphor-icons/core/light/arrow-right-light.svg?raw";
import ArrowRightSvgRegular from "@phosphor-icons/core/regular/arrow-right.svg?raw";
import ArrowRightSvgThin from "@phosphor-icons/core/thin/arrow-right-thin.svg?raw";
import ArrowsLeftRightSvgBold from "@phosphor-icons/core/bold/arrows-left-right-bold.svg?raw";
import ArrowsLeftRightSvgDuotone from "@phosphor-icons/core/duotone/arrows-left-right-duotone.svg?raw";
import ArrowsLeftRightSvgFill from "@phosphor-icons/core/fill/arrows-left-right-fill.svg?raw";
import ArrowsLeftRightSvgLight from "@phosphor-icons/core/light/arrows-left-right-light.svg?raw";
import ArrowsLeftRightSvgRegular from "@phosphor-icons/core/regular/arrows-left-right.svg?raw";
import ArrowsLeftRightSvgThin from "@phosphor-icons/core/thin/arrows-left-right-thin.svg?raw";
import ArrowSquareOutSvgBold from "@phosphor-icons/core/bold/arrow-square-out-bold.svg?raw";
import ArrowSquareOutSvgDuotone from "@phosphor-icons/core/duotone/arrow-square-out-duotone.svg?raw";
import ArrowSquareOutSvgFill from "@phosphor-icons/core/fill/arrow-square-out-fill.svg?raw";
import ArrowSquareOutSvgLight from "@phosphor-icons/core/light/arrow-square-out-light.svg?raw";
import ArrowSquareOutSvgRegular from "@phosphor-icons/core/regular/arrow-square-out.svg?raw";
import ArrowSquareOutSvgThin from "@phosphor-icons/core/thin/arrow-square-out-thin.svg?raw";
import ArticleSvgBold from "@phosphor-icons/core/bold/article-bold.svg?raw";
import ArticleSvgDuotone from "@phosphor-icons/core/duotone/article-duotone.svg?raw";
import ArticleSvgFill from "@phosphor-icons/core/fill/article-fill.svg?raw";
import ArticleSvgLight from "@phosphor-icons/core/light/article-light.svg?raw";
import ArticleSvgRegular from "@phosphor-icons/core/regular/article.svg?raw";
import ArticleSvgThin from "@phosphor-icons/core/thin/article-thin.svg?raw";
import BellSvgBold from "@phosphor-icons/core/bold/bell-bold.svg?raw";
import BellSvgDuotone from "@phosphor-icons/core/duotone/bell-duotone.svg?raw";
import BellSvgFill from "@phosphor-icons/core/fill/bell-fill.svg?raw";
import BellSvgLight from "@phosphor-icons/core/light/bell-light.svg?raw";
import BellSvgRegular from "@phosphor-icons/core/regular/bell.svg?raw";
import BellSvgThin from "@phosphor-icons/core/thin/bell-thin.svg?raw";
import BookOpenSvgBold from "@phosphor-icons/core/bold/book-open-bold.svg?raw";
import BookOpenSvgDuotone from "@phosphor-icons/core/duotone/book-open-duotone.svg?raw";
import BookOpenSvgFill from "@phosphor-icons/core/fill/book-open-fill.svg?raw";
import BookOpenSvgLight from "@phosphor-icons/core/light/book-open-light.svg?raw";
import BookOpenSvgRegular from "@phosphor-icons/core/regular/book-open.svg?raw";
import BookOpenSvgThin from "@phosphor-icons/core/thin/book-open-thin.svg?raw";
import CalendarDotsSvgBold from "@phosphor-icons/core/bold/calendar-dots-bold.svg?raw";
import CalendarDotsSvgDuotone from "@phosphor-icons/core/duotone/calendar-dots-duotone.svg?raw";
import CalendarDotsSvgFill from "@phosphor-icons/core/fill/calendar-dots-fill.svg?raw";
import CalendarDotsSvgLight from "@phosphor-icons/core/light/calendar-dots-light.svg?raw";
import CalendarDotsSvgRegular from "@phosphor-icons/core/regular/calendar-dots.svg?raw";
import CalendarDotsSvgThin from "@phosphor-icons/core/thin/calendar-dots-thin.svg?raw";
import CaretDownSvgBold from "@phosphor-icons/core/bold/caret-down-bold.svg?raw";
import CaretDownSvgDuotone from "@phosphor-icons/core/duotone/caret-down-duotone.svg?raw";
import CaretDownSvgFill from "@phosphor-icons/core/fill/caret-down-fill.svg?raw";
import CaretDownSvgLight from "@phosphor-icons/core/light/caret-down-light.svg?raw";
import CaretDownSvgRegular from "@phosphor-icons/core/regular/caret-down.svg?raw";
import CaretDownSvgThin from "@phosphor-icons/core/thin/caret-down-thin.svg?raw";
import CaretUpDownSvgBold from "@phosphor-icons/core/bold/caret-up-down-bold.svg?raw";
import CaretUpDownSvgDuotone from "@phosphor-icons/core/duotone/caret-up-down-duotone.svg?raw";
import CaretUpDownSvgFill from "@phosphor-icons/core/fill/caret-up-down-fill.svg?raw";
import CaretUpDownSvgLight from "@phosphor-icons/core/light/caret-up-down-light.svg?raw";
import CaretUpDownSvgRegular from "@phosphor-icons/core/regular/caret-up-down.svg?raw";
import CaretUpDownSvgThin from "@phosphor-icons/core/thin/caret-up-down-thin.svg?raw";
import ChartBarSvgBold from "@phosphor-icons/core/bold/chart-bar-bold.svg?raw";
import ChartBarSvgDuotone from "@phosphor-icons/core/duotone/chart-bar-duotone.svg?raw";
import ChartBarSvgFill from "@phosphor-icons/core/fill/chart-bar-fill.svg?raw";
import ChartBarSvgLight from "@phosphor-icons/core/light/chart-bar-light.svg?raw";
import ChartBarSvgRegular from "@phosphor-icons/core/regular/chart-bar.svg?raw";
import ChartBarSvgThin from "@phosphor-icons/core/thin/chart-bar-thin.svg?raw";
import ChartLineSvgBold from "@phosphor-icons/core/bold/chart-line-bold.svg?raw";
import ChartLineSvgDuotone from "@phosphor-icons/core/duotone/chart-line-duotone.svg?raw";
import ChartLineSvgFill from "@phosphor-icons/core/fill/chart-line-fill.svg?raw";
import ChartLineSvgLight from "@phosphor-icons/core/light/chart-line-light.svg?raw";
import ChartLineSvgRegular from "@phosphor-icons/core/regular/chart-line.svg?raw";
import ChartLineSvgThin from "@phosphor-icons/core/thin/chart-line-thin.svg?raw";
import ChartPieSvgBold from "@phosphor-icons/core/bold/chart-pie-bold.svg?raw";
import ChartPieSvgDuotone from "@phosphor-icons/core/duotone/chart-pie-duotone.svg?raw";
import ChartPieSvgFill from "@phosphor-icons/core/fill/chart-pie-fill.svg?raw";
import ChartPieSvgLight from "@phosphor-icons/core/light/chart-pie-light.svg?raw";
import ChartPieSvgRegular from "@phosphor-icons/core/regular/chart-pie.svg?raw";
import ChartPieSvgThin from "@phosphor-icons/core/thin/chart-pie-thin.svg?raw";
import ChatCircleSvgBold from "@phosphor-icons/core/bold/chat-circle-bold.svg?raw";
import ChatCircleSvgDuotone from "@phosphor-icons/core/duotone/chat-circle-duotone.svg?raw";
import ChatCircleSvgFill from "@phosphor-icons/core/fill/chat-circle-fill.svg?raw";
import ChatCircleSvgLight from "@phosphor-icons/core/light/chat-circle-light.svg?raw";
import ChatCircleSvgRegular from "@phosphor-icons/core/regular/chat-circle.svg?raw";
import ChatCircleSvgThin from "@phosphor-icons/core/thin/chat-circle-thin.svg?raw";
import CheckCircleSvgBold from "@phosphor-icons/core/bold/check-circle-bold.svg?raw";
import CheckCircleSvgDuotone from "@phosphor-icons/core/duotone/check-circle-duotone.svg?raw";
import CheckCircleSvgFill from "@phosphor-icons/core/fill/check-circle-fill.svg?raw";
import CheckCircleSvgLight from "@phosphor-icons/core/light/check-circle-light.svg?raw";
import CheckCircleSvgRegular from "@phosphor-icons/core/regular/check-circle.svg?raw";
import CheckCircleSvgThin from "@phosphor-icons/core/thin/check-circle-thin.svg?raw";
import CheckSvgBold from "@phosphor-icons/core/bold/check-bold.svg?raw";
import CheckSvgDuotone from "@phosphor-icons/core/duotone/check-duotone.svg?raw";
import CheckSvgFill from "@phosphor-icons/core/fill/check-fill.svg?raw";
import CheckSvgLight from "@phosphor-icons/core/light/check-light.svg?raw";
import CheckSvgRegular from "@phosphor-icons/core/regular/check.svg?raw";
import CheckSvgThin from "@phosphor-icons/core/thin/check-thin.svg?raw";
import ClockCounterClockwiseSvgBold from "@phosphor-icons/core/bold/clock-counter-clockwise-bold.svg?raw";
import ClockCounterClockwiseSvgDuotone from "@phosphor-icons/core/duotone/clock-counter-clockwise-duotone.svg?raw";
import ClockCounterClockwiseSvgFill from "@phosphor-icons/core/fill/clock-counter-clockwise-fill.svg?raw";
import ClockCounterClockwiseSvgLight from "@phosphor-icons/core/light/clock-counter-clockwise-light.svg?raw";
import ClockCounterClockwiseSvgRegular from "@phosphor-icons/core/regular/clock-counter-clockwise.svg?raw";
import ClockCounterClockwiseSvgThin from "@phosphor-icons/core/thin/clock-counter-clockwise-thin.svg?raw";
import CloudSlashSvgBold from "@phosphor-icons/core/bold/cloud-slash-bold.svg?raw";
import CloudSlashSvgDuotone from "@phosphor-icons/core/duotone/cloud-slash-duotone.svg?raw";
import CloudSlashSvgFill from "@phosphor-icons/core/fill/cloud-slash-fill.svg?raw";
import CloudSlashSvgLight from "@phosphor-icons/core/light/cloud-slash-light.svg?raw";
import CloudSlashSvgRegular from "@phosphor-icons/core/regular/cloud-slash.svg?raw";
import CloudSlashSvgThin from "@phosphor-icons/core/thin/cloud-slash-thin.svg?raw";
import CloudSvgBold from "@phosphor-icons/core/bold/cloud-bold.svg?raw";
import CloudSvgDuotone from "@phosphor-icons/core/duotone/cloud-duotone.svg?raw";
import CloudSvgFill from "@phosphor-icons/core/fill/cloud-fill.svg?raw";
import CloudSvgLight from "@phosphor-icons/core/light/cloud-light.svg?raw";
import CloudSvgRegular from "@phosphor-icons/core/regular/cloud.svg?raw";
import CloudSvgThin from "@phosphor-icons/core/thin/cloud-thin.svg?raw";
import CodeSvgBold from "@phosphor-icons/core/bold/code-bold.svg?raw";
import CodeSvgDuotone from "@phosphor-icons/core/duotone/code-duotone.svg?raw";
import CodeSvgFill from "@phosphor-icons/core/fill/code-fill.svg?raw";
import CodeSvgLight from "@phosphor-icons/core/light/code-light.svg?raw";
import CodeSvgRegular from "@phosphor-icons/core/regular/code.svg?raw";
import CodeSvgThin from "@phosphor-icons/core/thin/code-thin.svg?raw";
import CopySimpleSvgBold from "@phosphor-icons/core/bold/copy-simple-bold.svg?raw";
import CopySimpleSvgDuotone from "@phosphor-icons/core/duotone/copy-simple-duotone.svg?raw";
import CopySimpleSvgFill from "@phosphor-icons/core/fill/copy-simple-fill.svg?raw";
import CopySimpleSvgLight from "@phosphor-icons/core/light/copy-simple-light.svg?raw";
import CopySimpleSvgRegular from "@phosphor-icons/core/regular/copy-simple.svg?raw";
import CopySimpleSvgThin from "@phosphor-icons/core/thin/copy-simple-thin.svg?raw";
import CopySvgBold from "@phosphor-icons/core/bold/copy-bold.svg?raw";
import CopySvgDuotone from "@phosphor-icons/core/duotone/copy-duotone.svg?raw";
import CopySvgFill from "@phosphor-icons/core/fill/copy-fill.svg?raw";
import CopySvgLight from "@phosphor-icons/core/light/copy-light.svg?raw";
import CopySvgRegular from "@phosphor-icons/core/regular/copy.svg?raw";
import CopySvgThin from "@phosphor-icons/core/thin/copy-thin.svg?raw";
import CreditCardSvgBold from "@phosphor-icons/core/bold/credit-card-bold.svg?raw";
import CreditCardSvgDuotone from "@phosphor-icons/core/duotone/credit-card-duotone.svg?raw";
import CreditCardSvgFill from "@phosphor-icons/core/fill/credit-card-fill.svg?raw";
import CreditCardSvgLight from "@phosphor-icons/core/light/credit-card-light.svg?raw";
import CreditCardSvgRegular from "@phosphor-icons/core/regular/credit-card.svg?raw";
import CreditCardSvgThin from "@phosphor-icons/core/thin/credit-card-thin.svg?raw";
import CubeSvgBold from "@phosphor-icons/core/bold/cube-bold.svg?raw";
import CubeSvgDuotone from "@phosphor-icons/core/duotone/cube-duotone.svg?raw";
import CubeSvgFill from "@phosphor-icons/core/fill/cube-fill.svg?raw";
import CubeSvgLight from "@phosphor-icons/core/light/cube-light.svg?raw";
import CubeSvgRegular from "@phosphor-icons/core/regular/cube.svg?raw";
import CubeSvgThin from "@phosphor-icons/core/thin/cube-thin.svg?raw";
import DatabaseSvgBold from "@phosphor-icons/core/bold/database-bold.svg?raw";
import DatabaseSvgDuotone from "@phosphor-icons/core/duotone/database-duotone.svg?raw";
import DatabaseSvgFill from "@phosphor-icons/core/fill/database-fill.svg?raw";
import DatabaseSvgLight from "@phosphor-icons/core/light/database-light.svg?raw";
import DatabaseSvgRegular from "@phosphor-icons/core/regular/database.svg?raw";
import DatabaseSvgThin from "@phosphor-icons/core/thin/database-thin.svg?raw";
import DotsThreeSvgBold from "@phosphor-icons/core/bold/dots-three-bold.svg?raw";
import DotsThreeSvgDuotone from "@phosphor-icons/core/duotone/dots-three-duotone.svg?raw";
import DotsThreeSvgFill from "@phosphor-icons/core/fill/dots-three-fill.svg?raw";
import DotsThreeSvgLight from "@phosphor-icons/core/light/dots-three-light.svg?raw";
import DotsThreeSvgRegular from "@phosphor-icons/core/regular/dots-three.svg?raw";
import DotsThreeSvgThin from "@phosphor-icons/core/thin/dots-three-thin.svg?raw";
import DownloadSimpleSvgBold from "@phosphor-icons/core/bold/download-simple-bold.svg?raw";
import DownloadSimpleSvgDuotone from "@phosphor-icons/core/duotone/download-simple-duotone.svg?raw";
import DownloadSimpleSvgFill from "@phosphor-icons/core/fill/download-simple-fill.svg?raw";
import DownloadSimpleSvgLight from "@phosphor-icons/core/light/download-simple-light.svg?raw";
import DownloadSimpleSvgRegular from "@phosphor-icons/core/regular/download-simple.svg?raw";
import DownloadSimpleSvgThin from "@phosphor-icons/core/thin/download-simple-thin.svg?raw";
import EnvelopeSimpleSvgBold from "@phosphor-icons/core/bold/envelope-simple-bold.svg?raw";
import EnvelopeSimpleSvgDuotone from "@phosphor-icons/core/duotone/envelope-simple-duotone.svg?raw";
import EnvelopeSimpleSvgFill from "@phosphor-icons/core/fill/envelope-simple-fill.svg?raw";
import EnvelopeSimpleSvgLight from "@phosphor-icons/core/light/envelope-simple-light.svg?raw";
import EnvelopeSimpleSvgRegular from "@phosphor-icons/core/regular/envelope-simple.svg?raw";
import EnvelopeSimpleSvgThin from "@phosphor-icons/core/thin/envelope-simple-thin.svg?raw";
import EyeSlashSvgBold from "@phosphor-icons/core/bold/eye-slash-bold.svg?raw";
import EyeSlashSvgDuotone from "@phosphor-icons/core/duotone/eye-slash-duotone.svg?raw";
import EyeSlashSvgFill from "@phosphor-icons/core/fill/eye-slash-fill.svg?raw";
import EyeSlashSvgLight from "@phosphor-icons/core/light/eye-slash-light.svg?raw";
import EyeSlashSvgRegular from "@phosphor-icons/core/regular/eye-slash.svg?raw";
import EyeSlashSvgThin from "@phosphor-icons/core/thin/eye-slash-thin.svg?raw";
import EyeSvgBold from "@phosphor-icons/core/bold/eye-bold.svg?raw";
import EyeSvgDuotone from "@phosphor-icons/core/duotone/eye-duotone.svg?raw";
import EyeSvgFill from "@phosphor-icons/core/fill/eye-fill.svg?raw";
import EyeSvgLight from "@phosphor-icons/core/light/eye-light.svg?raw";
import EyeSvgRegular from "@phosphor-icons/core/regular/eye.svg?raw";
import EyeSvgThin from "@phosphor-icons/core/thin/eye-thin.svg?raw";
import FileMagnifyingGlassSvgBold from "@phosphor-icons/core/bold/file-magnifying-glass-bold.svg?raw";
import FileMagnifyingGlassSvgDuotone from "@phosphor-icons/core/duotone/file-magnifying-glass-duotone.svg?raw";
import FileMagnifyingGlassSvgFill from "@phosphor-icons/core/fill/file-magnifying-glass-fill.svg?raw";
import FileMagnifyingGlassSvgLight from "@phosphor-icons/core/light/file-magnifying-glass-light.svg?raw";
import FileMagnifyingGlassSvgRegular from "@phosphor-icons/core/regular/file-magnifying-glass.svg?raw";
import FileMagnifyingGlassSvgThin from "@phosphor-icons/core/thin/file-magnifying-glass-thin.svg?raw";
import FileMdSvgBold from "@phosphor-icons/core/bold/file-md-bold.svg?raw";
import FileMdSvgDuotone from "@phosphor-icons/core/duotone/file-md-duotone.svg?raw";
import FileMdSvgFill from "@phosphor-icons/core/fill/file-md-fill.svg?raw";
import FileMdSvgLight from "@phosphor-icons/core/light/file-md-light.svg?raw";
import FileMdSvgRegular from "@phosphor-icons/core/regular/file-md.svg?raw";
import FileMdSvgThin from "@phosphor-icons/core/thin/file-md-thin.svg?raw";
import FileSvgBold from "@phosphor-icons/core/bold/file-bold.svg?raw";
import FileSvgDuotone from "@phosphor-icons/core/duotone/file-duotone.svg?raw";
import FileSvgFill from "@phosphor-icons/core/fill/file-fill.svg?raw";
import FileSvgLight from "@phosphor-icons/core/light/file-light.svg?raw";
import FileSvgRegular from "@phosphor-icons/core/regular/file.svg?raw";
import FileSvgThin from "@phosphor-icons/core/thin/file-thin.svg?raw";
import FolderOpenSvgBold from "@phosphor-icons/core/bold/folder-open-bold.svg?raw";
import FolderOpenSvgDuotone from "@phosphor-icons/core/duotone/folder-open-duotone.svg?raw";
import FolderOpenSvgFill from "@phosphor-icons/core/fill/folder-open-fill.svg?raw";
import FolderOpenSvgLight from "@phosphor-icons/core/light/folder-open-light.svg?raw";
import FolderOpenSvgRegular from "@phosphor-icons/core/regular/folder-open.svg?raw";
import FolderOpenSvgThin from "@phosphor-icons/core/thin/folder-open-thin.svg?raw";
import FolderSvgBold from "@phosphor-icons/core/bold/folder-bold.svg?raw";
import FolderSvgDuotone from "@phosphor-icons/core/duotone/folder-duotone.svg?raw";
import FolderSvgFill from "@phosphor-icons/core/fill/folder-fill.svg?raw";
import FolderSvgLight from "@phosphor-icons/core/light/folder-light.svg?raw";
import FolderSvgRegular from "@phosphor-icons/core/regular/folder.svg?raw";
import FolderSvgThin from "@phosphor-icons/core/thin/folder-thin.svg?raw";
import FunnelSimpleSvgBold from "@phosphor-icons/core/bold/funnel-simple-bold.svg?raw";
import FunnelSimpleSvgDuotone from "@phosphor-icons/core/duotone/funnel-simple-duotone.svg?raw";
import FunnelSimpleSvgFill from "@phosphor-icons/core/fill/funnel-simple-fill.svg?raw";
import FunnelSimpleSvgLight from "@phosphor-icons/core/light/funnel-simple-light.svg?raw";
import FunnelSimpleSvgRegular from "@phosphor-icons/core/regular/funnel-simple.svg?raw";
import FunnelSimpleSvgThin from "@phosphor-icons/core/thin/funnel-simple-thin.svg?raw";
import GearSixSvgBold from "@phosphor-icons/core/bold/gear-six-bold.svg?raw";
import GearSixSvgDuotone from "@phosphor-icons/core/duotone/gear-six-duotone.svg?raw";
import GearSixSvgFill from "@phosphor-icons/core/fill/gear-six-fill.svg?raw";
import GearSixSvgLight from "@phosphor-icons/core/light/gear-six-light.svg?raw";
import GearSixSvgRegular from "@phosphor-icons/core/regular/gear-six.svg?raw";
import GearSixSvgThin from "@phosphor-icons/core/thin/gear-six-thin.svg?raw";
import GearSvgBold from "@phosphor-icons/core/bold/gear-bold.svg?raw";
import GearSvgDuotone from "@phosphor-icons/core/duotone/gear-duotone.svg?raw";
import GearSvgFill from "@phosphor-icons/core/fill/gear-fill.svg?raw";
import GearSvgLight from "@phosphor-icons/core/light/gear-light.svg?raw";
import GearSvgRegular from "@phosphor-icons/core/regular/gear.svg?raw";
import GearSvgThin from "@phosphor-icons/core/thin/gear-thin.svg?raw";
import GithubLogoSvgBold from "@phosphor-icons/core/bold/github-logo-bold.svg?raw";
import GithubLogoSvgDuotone from "@phosphor-icons/core/duotone/github-logo-duotone.svg?raw";
import GithubLogoSvgFill from "@phosphor-icons/core/fill/github-logo-fill.svg?raw";
import GithubLogoSvgLight from "@phosphor-icons/core/light/github-logo-light.svg?raw";
import GithubLogoSvgRegular from "@phosphor-icons/core/regular/github-logo.svg?raw";
import GithubLogoSvgThin from "@phosphor-icons/core/thin/github-logo-thin.svg?raw";
import GlobeSvgBold from "@phosphor-icons/core/bold/globe-bold.svg?raw";
import GlobeSvgDuotone from "@phosphor-icons/core/duotone/globe-duotone.svg?raw";
import GlobeSvgFill from "@phosphor-icons/core/fill/globe-fill.svg?raw";
import GlobeSvgLight from "@phosphor-icons/core/light/globe-light.svg?raw";
import GlobeSvgRegular from "@phosphor-icons/core/regular/globe.svg?raw";
import GlobeSvgThin from "@phosphor-icons/core/thin/globe-thin.svg?raw";
import HouseSvgBold from "@phosphor-icons/core/bold/house-bold.svg?raw";
import HouseSvgDuotone from "@phosphor-icons/core/duotone/house-duotone.svg?raw";
import HouseSvgFill from "@phosphor-icons/core/fill/house-fill.svg?raw";
import HouseSvgLight from "@phosphor-icons/core/light/house-light.svg?raw";
import HouseSvgRegular from "@phosphor-icons/core/regular/house.svg?raw";
import HouseSvgThin from "@phosphor-icons/core/thin/house-thin.svg?raw";
import ImagesSvgBold from "@phosphor-icons/core/bold/images-bold.svg?raw";
import ImagesSvgDuotone from "@phosphor-icons/core/duotone/images-duotone.svg?raw";
import ImagesSvgFill from "@phosphor-icons/core/fill/images-fill.svg?raw";
import ImagesSvgLight from "@phosphor-icons/core/light/images-light.svg?raw";
import ImagesSvgRegular from "@phosphor-icons/core/regular/images.svg?raw";
import ImagesSvgThin from "@phosphor-icons/core/thin/images-thin.svg?raw";
import InfoSvgBold from "@phosphor-icons/core/bold/info-bold.svg?raw";
import InfoSvgDuotone from "@phosphor-icons/core/duotone/info-duotone.svg?raw";
import InfoSvgFill from "@phosphor-icons/core/fill/info-fill.svg?raw";
import InfoSvgLight from "@phosphor-icons/core/light/info-light.svg?raw";
import InfoSvgRegular from "@phosphor-icons/core/regular/info.svg?raw";
import InfoSvgThin from "@phosphor-icons/core/thin/info-thin.svg?raw";
import LinkSimpleSvgBold from "@phosphor-icons/core/bold/link-simple-bold.svg?raw";
import LinkSimpleSvgDuotone from "@phosphor-icons/core/duotone/link-simple-duotone.svg?raw";
import LinkSimpleSvgFill from "@phosphor-icons/core/fill/link-simple-fill.svg?raw";
import LinkSimpleSvgLight from "@phosphor-icons/core/light/link-simple-light.svg?raw";
import LinkSimpleSvgRegular from "@phosphor-icons/core/regular/link-simple.svg?raw";
import LinkSimpleSvgThin from "@phosphor-icons/core/thin/link-simple-thin.svg?raw";
import LinkSvgBold from "@phosphor-icons/core/bold/link-bold.svg?raw";
import LinkSvgDuotone from "@phosphor-icons/core/duotone/link-duotone.svg?raw";
import LinkSvgFill from "@phosphor-icons/core/fill/link-fill.svg?raw";
import LinkSvgLight from "@phosphor-icons/core/light/link-light.svg?raw";
import LinkSvgRegular from "@phosphor-icons/core/regular/link.svg?raw";
import LinkSvgThin from "@phosphor-icons/core/thin/link-thin.svg?raw";
import LockSvgBold from "@phosphor-icons/core/bold/lock-bold.svg?raw";
import LockSvgDuotone from "@phosphor-icons/core/duotone/lock-duotone.svg?raw";
import LockSvgFill from "@phosphor-icons/core/fill/lock-fill.svg?raw";
import LockSvgLight from "@phosphor-icons/core/light/lock-light.svg?raw";
import LockSvgRegular from "@phosphor-icons/core/regular/lock.svg?raw";
import LockSvgThin from "@phosphor-icons/core/thin/lock-thin.svg?raw";
import MagnifyingGlassSvgBold from "@phosphor-icons/core/bold/magnifying-glass-bold.svg?raw";
import MagnifyingGlassSvgDuotone from "@phosphor-icons/core/duotone/magnifying-glass-duotone.svg?raw";
import MagnifyingGlassSvgFill from "@phosphor-icons/core/fill/magnifying-glass-fill.svg?raw";
import MagnifyingGlassSvgLight from "@phosphor-icons/core/light/magnifying-glass-light.svg?raw";
import MagnifyingGlassSvgRegular from "@phosphor-icons/core/regular/magnifying-glass.svg?raw";
import MagnifyingGlassSvgThin from "@phosphor-icons/core/thin/magnifying-glass-thin.svg?raw";
import MinusSvgBold from "@phosphor-icons/core/bold/minus-bold.svg?raw";
import MinusSvgDuotone from "@phosphor-icons/core/duotone/minus-duotone.svg?raw";
import MinusSvgFill from "@phosphor-icons/core/fill/minus-fill.svg?raw";
import MinusSvgLight from "@phosphor-icons/core/light/minus-light.svg?raw";
import MinusSvgRegular from "@phosphor-icons/core/regular/minus.svg?raw";
import MinusSvgThin from "@phosphor-icons/core/thin/minus-thin.svg?raw";
import MoonSvgBold from "@phosphor-icons/core/bold/moon-bold.svg?raw";
import MoonSvgDuotone from "@phosphor-icons/core/duotone/moon-duotone.svg?raw";
import MoonSvgFill from "@phosphor-icons/core/fill/moon-fill.svg?raw";
import MoonSvgLight from "@phosphor-icons/core/light/moon-light.svg?raw";
import MoonSvgRegular from "@phosphor-icons/core/regular/moon.svg?raw";
import MoonSvgThin from "@phosphor-icons/core/thin/moon-thin.svg?raw";
import NewspaperSvgBold from "@phosphor-icons/core/bold/newspaper-bold.svg?raw";
import NewspaperSvgDuotone from "@phosphor-icons/core/duotone/newspaper-duotone.svg?raw";
import NewspaperSvgFill from "@phosphor-icons/core/fill/newspaper-fill.svg?raw";
import NewspaperSvgLight from "@phosphor-icons/core/light/newspaper-light.svg?raw";
import NewspaperSvgRegular from "@phosphor-icons/core/regular/newspaper.svg?raw";
import NewspaperSvgThin from "@phosphor-icons/core/thin/newspaper-thin.svg?raw";
import OpenAiLogoSvgBold from "@phosphor-icons/core/bold/open-ai-logo-bold.svg?raw";
import OpenAiLogoSvgDuotone from "@phosphor-icons/core/duotone/open-ai-logo-duotone.svg?raw";
import OpenAiLogoSvgFill from "@phosphor-icons/core/fill/open-ai-logo-fill.svg?raw";
import OpenAiLogoSvgLight from "@phosphor-icons/core/light/open-ai-logo-light.svg?raw";
import OpenAiLogoSvgRegular from "@phosphor-icons/core/regular/open-ai-logo.svg?raw";
import OpenAiLogoSvgThin from "@phosphor-icons/core/thin/open-ai-logo-thin.svg?raw";
import PackageSvgBold from "@phosphor-icons/core/bold/package-bold.svg?raw";
import PackageSvgDuotone from "@phosphor-icons/core/duotone/package-duotone.svg?raw";
import PackageSvgFill from "@phosphor-icons/core/fill/package-fill.svg?raw";
import PackageSvgLight from "@phosphor-icons/core/light/package-light.svg?raw";
import PackageSvgRegular from "@phosphor-icons/core/regular/package.svg?raw";
import PackageSvgThin from "@phosphor-icons/core/thin/package-thin.svg?raw";
import PaletteSvgBold from "@phosphor-icons/core/bold/palette-bold.svg?raw";
import PaletteSvgDuotone from "@phosphor-icons/core/duotone/palette-duotone.svg?raw";
import PaletteSvgFill from "@phosphor-icons/core/fill/palette-fill.svg?raw";
import PaletteSvgLight from "@phosphor-icons/core/light/palette-light.svg?raw";
import PaletteSvgRegular from "@phosphor-icons/core/regular/palette.svg?raw";
import PaletteSvgThin from "@phosphor-icons/core/thin/palette-thin.svg?raw";
import PencilRulerSvgBold from "@phosphor-icons/core/bold/pencil-ruler-bold.svg?raw";
import PencilRulerSvgDuotone from "@phosphor-icons/core/duotone/pencil-ruler-duotone.svg?raw";
import PencilRulerSvgFill from "@phosphor-icons/core/fill/pencil-ruler-fill.svg?raw";
import PencilRulerSvgLight from "@phosphor-icons/core/light/pencil-ruler-light.svg?raw";
import PencilRulerSvgRegular from "@phosphor-icons/core/regular/pencil-ruler.svg?raw";
import PencilRulerSvgThin from "@phosphor-icons/core/thin/pencil-ruler-thin.svg?raw";
import PencilSimpleSvgBold from "@phosphor-icons/core/bold/pencil-simple-bold.svg?raw";
import PencilSimpleSvgDuotone from "@phosphor-icons/core/duotone/pencil-simple-duotone.svg?raw";
import PencilSimpleSvgFill from "@phosphor-icons/core/fill/pencil-simple-fill.svg?raw";
import PencilSimpleSvgLight from "@phosphor-icons/core/light/pencil-simple-light.svg?raw";
import PencilSimpleSvgRegular from "@phosphor-icons/core/regular/pencil-simple.svg?raw";
import PencilSimpleSvgThin from "@phosphor-icons/core/thin/pencil-simple-thin.svg?raw";
import PlugsConnectedSvgBold from "@phosphor-icons/core/bold/plugs-connected-bold.svg?raw";
import PlugsConnectedSvgDuotone from "@phosphor-icons/core/duotone/plugs-connected-duotone.svg?raw";
import PlugsConnectedSvgFill from "@phosphor-icons/core/fill/plugs-connected-fill.svg?raw";
import PlugsConnectedSvgLight from "@phosphor-icons/core/light/plugs-connected-light.svg?raw";
import PlugsConnectedSvgRegular from "@phosphor-icons/core/regular/plugs-connected.svg?raw";
import PlugsConnectedSvgThin from "@phosphor-icons/core/thin/plugs-connected-thin.svg?raw";
import PlusSvgBold from "@phosphor-icons/core/bold/plus-bold.svg?raw";
import PlusSvgDuotone from "@phosphor-icons/core/duotone/plus-duotone.svg?raw";
import PlusSvgFill from "@phosphor-icons/core/fill/plus-fill.svg?raw";
import PlusSvgLight from "@phosphor-icons/core/light/plus-light.svg?raw";
import PlusSvgRegular from "@phosphor-icons/core/regular/plus.svg?raw";
import PlusSvgThin from "@phosphor-icons/core/thin/plus-thin.svg?raw";
import QuestionSvgBold from "@phosphor-icons/core/bold/question-bold.svg?raw";
import QuestionSvgDuotone from "@phosphor-icons/core/duotone/question-duotone.svg?raw";
import QuestionSvgFill from "@phosphor-icons/core/fill/question-fill.svg?raw";
import QuestionSvgLight from "@phosphor-icons/core/light/question-light.svg?raw";
import QuestionSvgRegular from "@phosphor-icons/core/regular/question.svg?raw";
import QuestionSvgThin from "@phosphor-icons/core/thin/question-thin.svg?raw";
import ShieldCheckSvgBold from "@phosphor-icons/core/bold/shield-check-bold.svg?raw";
import ShieldCheckSvgDuotone from "@phosphor-icons/core/duotone/shield-check-duotone.svg?raw";
import ShieldCheckSvgFill from "@phosphor-icons/core/fill/shield-check-fill.svg?raw";
import ShieldCheckSvgLight from "@phosphor-icons/core/light/shield-check-light.svg?raw";
import ShieldCheckSvgRegular from "@phosphor-icons/core/regular/shield-check.svg?raw";
import ShieldCheckSvgThin from "@phosphor-icons/core/thin/shield-check-thin.svg?raw";
import SignOutSvgBold from "@phosphor-icons/core/bold/sign-out-bold.svg?raw";
import SignOutSvgDuotone from "@phosphor-icons/core/duotone/sign-out-duotone.svg?raw";
import SignOutSvgFill from "@phosphor-icons/core/fill/sign-out-fill.svg?raw";
import SignOutSvgLight from "@phosphor-icons/core/light/sign-out-light.svg?raw";
import SignOutSvgRegular from "@phosphor-icons/core/regular/sign-out.svg?raw";
import SignOutSvgThin from "@phosphor-icons/core/thin/sign-out-thin.svg?raw";
import SquaresFourSvgBold from "@phosphor-icons/core/bold/squares-four-bold.svg?raw";
import SquaresFourSvgDuotone from "@phosphor-icons/core/duotone/squares-four-duotone.svg?raw";
import SquaresFourSvgFill from "@phosphor-icons/core/fill/squares-four-fill.svg?raw";
import SquaresFourSvgLight from "@phosphor-icons/core/light/squares-four-light.svg?raw";
import SquaresFourSvgRegular from "@phosphor-icons/core/regular/squares-four.svg?raw";
import SquaresFourSvgThin from "@phosphor-icons/core/thin/squares-four-thin.svg?raw";
import StackSimpleSvgBold from "@phosphor-icons/core/bold/stack-simple-bold.svg?raw";
import StackSimpleSvgDuotone from "@phosphor-icons/core/duotone/stack-simple-duotone.svg?raw";
import StackSimpleSvgFill from "@phosphor-icons/core/fill/stack-simple-fill.svg?raw";
import StackSimpleSvgLight from "@phosphor-icons/core/light/stack-simple-light.svg?raw";
import StackSimpleSvgRegular from "@phosphor-icons/core/regular/stack-simple.svg?raw";
import StackSimpleSvgThin from "@phosphor-icons/core/thin/stack-simple-thin.svg?raw";
import StackSvgBold from "@phosphor-icons/core/bold/stack-bold.svg?raw";
import StackSvgDuotone from "@phosphor-icons/core/duotone/stack-duotone.svg?raw";
import StackSvgFill from "@phosphor-icons/core/fill/stack-fill.svg?raw";
import StackSvgLight from "@phosphor-icons/core/light/stack-light.svg?raw";
import StackSvgRegular from "@phosphor-icons/core/regular/stack.svg?raw";
import StackSvgThin from "@phosphor-icons/core/thin/stack-thin.svg?raw";
import SunSvgBold from "@phosphor-icons/core/bold/sun-bold.svg?raw";
import SunSvgDuotone from "@phosphor-icons/core/duotone/sun-duotone.svg?raw";
import SunSvgFill from "@phosphor-icons/core/fill/sun-fill.svg?raw";
import SunSvgLight from "@phosphor-icons/core/light/sun-light.svg?raw";
import SunSvgRegular from "@phosphor-icons/core/regular/sun.svg?raw";
import SunSvgThin from "@phosphor-icons/core/thin/sun-thin.svg?raw";
import TextBSvgBold from "@phosphor-icons/core/bold/text-b-bold.svg?raw";
import TextBSvgDuotone from "@phosphor-icons/core/duotone/text-b-duotone.svg?raw";
import TextBSvgFill from "@phosphor-icons/core/fill/text-b-fill.svg?raw";
import TextBSvgLight from "@phosphor-icons/core/light/text-b-light.svg?raw";
import TextBSvgRegular from "@phosphor-icons/core/regular/text-b.svg?raw";
import TextBSvgThin from "@phosphor-icons/core/thin/text-b-thin.svg?raw";
import TextItalicSvgBold from "@phosphor-icons/core/bold/text-italic-bold.svg?raw";
import TextItalicSvgDuotone from "@phosphor-icons/core/duotone/text-italic-duotone.svg?raw";
import TextItalicSvgFill from "@phosphor-icons/core/fill/text-italic-fill.svg?raw";
import TextItalicSvgLight from "@phosphor-icons/core/light/text-italic-light.svg?raw";
import TextItalicSvgRegular from "@phosphor-icons/core/regular/text-italic.svg?raw";
import TextItalicSvgThin from "@phosphor-icons/core/thin/text-italic-thin.svg?raw";
import TranslateSvgBold from "@phosphor-icons/core/bold/translate-bold.svg?raw";
import TranslateSvgDuotone from "@phosphor-icons/core/duotone/translate-duotone.svg?raw";
import TranslateSvgFill from "@phosphor-icons/core/fill/translate-fill.svg?raw";
import TranslateSvgLight from "@phosphor-icons/core/light/translate-light.svg?raw";
import TranslateSvgRegular from "@phosphor-icons/core/regular/translate.svg?raw";
import TranslateSvgThin from "@phosphor-icons/core/thin/translate-thin.svg?raw";
import TrashSvgBold from "@phosphor-icons/core/bold/trash-bold.svg?raw";
import TrashSvgDuotone from "@phosphor-icons/core/duotone/trash-duotone.svg?raw";
import TrashSvgFill from "@phosphor-icons/core/fill/trash-fill.svg?raw";
import TrashSvgLight from "@phosphor-icons/core/light/trash-light.svg?raw";
import TrashSvgRegular from "@phosphor-icons/core/regular/trash.svg?raw";
import TrashSvgThin from "@phosphor-icons/core/thin/trash-thin.svg?raw";
import UploadSimpleSvgBold from "@phosphor-icons/core/bold/upload-simple-bold.svg?raw";
import UploadSimpleSvgDuotone from "@phosphor-icons/core/duotone/upload-simple-duotone.svg?raw";
import UploadSimpleSvgFill from "@phosphor-icons/core/fill/upload-simple-fill.svg?raw";
import UploadSimpleSvgLight from "@phosphor-icons/core/light/upload-simple-light.svg?raw";
import UploadSimpleSvgRegular from "@phosphor-icons/core/regular/upload-simple.svg?raw";
import UploadSimpleSvgThin from "@phosphor-icons/core/thin/upload-simple-thin.svg?raw";
import UsersSvgBold from "@phosphor-icons/core/bold/users-bold.svg?raw";
import UsersSvgDuotone from "@phosphor-icons/core/duotone/users-duotone.svg?raw";
import UsersSvgFill from "@phosphor-icons/core/fill/users-fill.svg?raw";
import UsersSvgLight from "@phosphor-icons/core/light/users-light.svg?raw";
import UsersSvgRegular from "@phosphor-icons/core/regular/users.svg?raw";
import UsersSvgThin from "@phosphor-icons/core/thin/users-thin.svg?raw";
import UserSvgBold from "@phosphor-icons/core/bold/user-bold.svg?raw";
import UserSvgDuotone from "@phosphor-icons/core/duotone/user-duotone.svg?raw";
import UserSvgFill from "@phosphor-icons/core/fill/user-fill.svg?raw";
import UserSvgLight from "@phosphor-icons/core/light/user-light.svg?raw";
import UserSvgRegular from "@phosphor-icons/core/regular/user.svg?raw";
import UserSvgThin from "@phosphor-icons/core/thin/user-thin.svg?raw";
import WarningCircleSvgBold from "@phosphor-icons/core/bold/warning-circle-bold.svg?raw";
import WarningCircleSvgDuotone from "@phosphor-icons/core/duotone/warning-circle-duotone.svg?raw";
import WarningCircleSvgFill from "@phosphor-icons/core/fill/warning-circle-fill.svg?raw";
import WarningCircleSvgLight from "@phosphor-icons/core/light/warning-circle-light.svg?raw";
import WarningCircleSvgRegular from "@phosphor-icons/core/regular/warning-circle.svg?raw";
import WarningCircleSvgThin from "@phosphor-icons/core/thin/warning-circle-thin.svg?raw";
import WarningOctagonSvgBold from "@phosphor-icons/core/bold/warning-octagon-bold.svg?raw";
import WarningOctagonSvgDuotone from "@phosphor-icons/core/duotone/warning-octagon-duotone.svg?raw";
import WarningOctagonSvgFill from "@phosphor-icons/core/fill/warning-octagon-fill.svg?raw";
import WarningOctagonSvgLight from "@phosphor-icons/core/light/warning-octagon-light.svg?raw";
import WarningOctagonSvgRegular from "@phosphor-icons/core/regular/warning-octagon.svg?raw";
import WarningOctagonSvgThin from "@phosphor-icons/core/thin/warning-octagon-thin.svg?raw";
import WarningSvgBold from "@phosphor-icons/core/bold/warning-bold.svg?raw";
import WarningSvgDuotone from "@phosphor-icons/core/duotone/warning-duotone.svg?raw";
import WarningSvgFill from "@phosphor-icons/core/fill/warning-fill.svg?raw";
import WarningSvgLight from "@phosphor-icons/core/light/warning-light.svg?raw";
import WarningSvgRegular from "@phosphor-icons/core/regular/warning.svg?raw";
import WarningSvgThin from "@phosphor-icons/core/thin/warning-thin.svg?raw";
import WrenchSvgBold from "@phosphor-icons/core/bold/wrench-bold.svg?raw";
import WrenchSvgDuotone from "@phosphor-icons/core/duotone/wrench-duotone.svg?raw";
import WrenchSvgFill from "@phosphor-icons/core/fill/wrench-fill.svg?raw";
import WrenchSvgLight from "@phosphor-icons/core/light/wrench-light.svg?raw";
import WrenchSvgRegular from "@phosphor-icons/core/regular/wrench.svg?raw";
import WrenchSvgThin from "@phosphor-icons/core/thin/wrench-thin.svg?raw";
import XCircleSvgBold from "@phosphor-icons/core/bold/x-circle-bold.svg?raw";
import XCircleSvgDuotone from "@phosphor-icons/core/duotone/x-circle-duotone.svg?raw";
import XCircleSvgFill from "@phosphor-icons/core/fill/x-circle-fill.svg?raw";
import XCircleSvgLight from "@phosphor-icons/core/light/x-circle-light.svg?raw";
import XCircleSvgRegular from "@phosphor-icons/core/regular/x-circle.svg?raw";
import XCircleSvgThin from "@phosphor-icons/core/thin/x-circle-thin.svg?raw";
import XSvgBold from "@phosphor-icons/core/bold/x-bold.svg?raw";
import XSvgDuotone from "@phosphor-icons/core/duotone/x-duotone.svg?raw";
import XSvgFill from "@phosphor-icons/core/fill/x-fill.svg?raw";
import XSvgLight from "@phosphor-icons/core/light/x-light.svg?raw";
import XSvgRegular from "@phosphor-icons/core/regular/x.svg?raw";
import XSvgThin from "@phosphor-icons/core/thin/x-thin.svg?raw";

export type IconWeight =
  | "bold"
  | "duotone"
  | "fill"
  | "light"
  | "regular"
  | "thin";

export type IconProps = Omit<
  JSX.SvgSVGAttributes<SVGSVGElement>,
  "color" | "height" | "width"
> & {
  alt?: string;
  className?: string;
  color?: string;
  mirrored?: boolean;
  size?: string | number;
  weight?: IconWeight;
};

type IconSources = Record<IconWeight, string>;

function svgBody(source: string) {
  return source.replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
}

function createIcon(sources: IconSources): Component<IconProps> {
  const bodies = Object.fromEntries(
    Object.entries(sources).map(([weight, source]) => [
      weight,
      svgBody(source),
    ]),
  ) as Record<IconWeight, string>;

  return (inputProps) => {
    const [props, rest] = splitProps(inputProps, [
      "alt",
      "class",
      "className",
      "color",
      "mirrored",
      "size",
      "weight",
    ]);

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width={props.size ?? "1em"}
        height={props.size ?? "1em"}
        class={props.class ?? props.className}
        fill={props.color ?? "currentColor"}
        viewBox="0 0 256 256"
        aria-hidden={props.alt ? undefined : "true"}
        role={props.alt ? "img" : undefined}
        {...rest}
      >
        {props.alt ? <title>{props.alt}</title> : null}
        <g
          transform={
            props.mirrored ? "translate(256 0) scale(-1 1)" : undefined
          }
          innerHTML={bodies[props.weight ?? "regular"]}
        />
      </svg>
    );
  };
}

const ArrowLeftSvg = createIcon({
  bold: ArrowLeftSvgBold,
  duotone: ArrowLeftSvgDuotone,
  fill: ArrowLeftSvgFill,
  light: ArrowLeftSvgLight,
  regular: ArrowLeftSvgRegular,
  thin: ArrowLeftSvgThin,
});

const ArrowRightSvg = createIcon({
  bold: ArrowRightSvgBold,
  duotone: ArrowRightSvgDuotone,
  fill: ArrowRightSvgFill,
  light: ArrowRightSvgLight,
  regular: ArrowRightSvgRegular,
  thin: ArrowRightSvgThin,
});

const ArrowsLeftRightSvg = createIcon({
  bold: ArrowsLeftRightSvgBold,
  duotone: ArrowsLeftRightSvgDuotone,
  fill: ArrowsLeftRightSvgFill,
  light: ArrowsLeftRightSvgLight,
  regular: ArrowsLeftRightSvgRegular,
  thin: ArrowsLeftRightSvgThin,
});

const ArrowSquareOutSvg = createIcon({
  bold: ArrowSquareOutSvgBold,
  duotone: ArrowSquareOutSvgDuotone,
  fill: ArrowSquareOutSvgFill,
  light: ArrowSquareOutSvgLight,
  regular: ArrowSquareOutSvgRegular,
  thin: ArrowSquareOutSvgThin,
});

const ArticleSvg = createIcon({
  bold: ArticleSvgBold,
  duotone: ArticleSvgDuotone,
  fill: ArticleSvgFill,
  light: ArticleSvgLight,
  regular: ArticleSvgRegular,
  thin: ArticleSvgThin,
});

const BellSvg = createIcon({
  bold: BellSvgBold,
  duotone: BellSvgDuotone,
  fill: BellSvgFill,
  light: BellSvgLight,
  regular: BellSvgRegular,
  thin: BellSvgThin,
});

const BookOpenSvg = createIcon({
  bold: BookOpenSvgBold,
  duotone: BookOpenSvgDuotone,
  fill: BookOpenSvgFill,
  light: BookOpenSvgLight,
  regular: BookOpenSvgRegular,
  thin: BookOpenSvgThin,
});

const CalendarDotsSvg = createIcon({
  bold: CalendarDotsSvgBold,
  duotone: CalendarDotsSvgDuotone,
  fill: CalendarDotsSvgFill,
  light: CalendarDotsSvgLight,
  regular: CalendarDotsSvgRegular,
  thin: CalendarDotsSvgThin,
});

const CaretDownSvg = createIcon({
  bold: CaretDownSvgBold,
  duotone: CaretDownSvgDuotone,
  fill: CaretDownSvgFill,
  light: CaretDownSvgLight,
  regular: CaretDownSvgRegular,
  thin: CaretDownSvgThin,
});

const CaretUpDownSvg = createIcon({
  bold: CaretUpDownSvgBold,
  duotone: CaretUpDownSvgDuotone,
  fill: CaretUpDownSvgFill,
  light: CaretUpDownSvgLight,
  regular: CaretUpDownSvgRegular,
  thin: CaretUpDownSvgThin,
});

const ChartBarSvg = createIcon({
  bold: ChartBarSvgBold,
  duotone: ChartBarSvgDuotone,
  fill: ChartBarSvgFill,
  light: ChartBarSvgLight,
  regular: ChartBarSvgRegular,
  thin: ChartBarSvgThin,
});

const ChartLineSvg = createIcon({
  bold: ChartLineSvgBold,
  duotone: ChartLineSvgDuotone,
  fill: ChartLineSvgFill,
  light: ChartLineSvgLight,
  regular: ChartLineSvgRegular,
  thin: ChartLineSvgThin,
});

const ChartPieSvg = createIcon({
  bold: ChartPieSvgBold,
  duotone: ChartPieSvgDuotone,
  fill: ChartPieSvgFill,
  light: ChartPieSvgLight,
  regular: ChartPieSvgRegular,
  thin: ChartPieSvgThin,
});

const ChatCircleSvg = createIcon({
  bold: ChatCircleSvgBold,
  duotone: ChatCircleSvgDuotone,
  fill: ChatCircleSvgFill,
  light: ChatCircleSvgLight,
  regular: ChatCircleSvgRegular,
  thin: ChatCircleSvgThin,
});

const CheckCircleSvg = createIcon({
  bold: CheckCircleSvgBold,
  duotone: CheckCircleSvgDuotone,
  fill: CheckCircleSvgFill,
  light: CheckCircleSvgLight,
  regular: CheckCircleSvgRegular,
  thin: CheckCircleSvgThin,
});

const CheckSvg = createIcon({
  bold: CheckSvgBold,
  duotone: CheckSvgDuotone,
  fill: CheckSvgFill,
  light: CheckSvgLight,
  regular: CheckSvgRegular,
  thin: CheckSvgThin,
});

const ClockCounterClockwiseSvg = createIcon({
  bold: ClockCounterClockwiseSvgBold,
  duotone: ClockCounterClockwiseSvgDuotone,
  fill: ClockCounterClockwiseSvgFill,
  light: ClockCounterClockwiseSvgLight,
  regular: ClockCounterClockwiseSvgRegular,
  thin: ClockCounterClockwiseSvgThin,
});

const CloudSlashSvg = createIcon({
  bold: CloudSlashSvgBold,
  duotone: CloudSlashSvgDuotone,
  fill: CloudSlashSvgFill,
  light: CloudSlashSvgLight,
  regular: CloudSlashSvgRegular,
  thin: CloudSlashSvgThin,
});

const CloudSvg = createIcon({
  bold: CloudSvgBold,
  duotone: CloudSvgDuotone,
  fill: CloudSvgFill,
  light: CloudSvgLight,
  regular: CloudSvgRegular,
  thin: CloudSvgThin,
});

const CodeSvg = createIcon({
  bold: CodeSvgBold,
  duotone: CodeSvgDuotone,
  fill: CodeSvgFill,
  light: CodeSvgLight,
  regular: CodeSvgRegular,
  thin: CodeSvgThin,
});

const CopySimpleSvg = createIcon({
  bold: CopySimpleSvgBold,
  duotone: CopySimpleSvgDuotone,
  fill: CopySimpleSvgFill,
  light: CopySimpleSvgLight,
  regular: CopySimpleSvgRegular,
  thin: CopySimpleSvgThin,
});

const CopySvg = createIcon({
  bold: CopySvgBold,
  duotone: CopySvgDuotone,
  fill: CopySvgFill,
  light: CopySvgLight,
  regular: CopySvgRegular,
  thin: CopySvgThin,
});

const CreditCardSvg = createIcon({
  bold: CreditCardSvgBold,
  duotone: CreditCardSvgDuotone,
  fill: CreditCardSvgFill,
  light: CreditCardSvgLight,
  regular: CreditCardSvgRegular,
  thin: CreditCardSvgThin,
});

const CubeSvg = createIcon({
  bold: CubeSvgBold,
  duotone: CubeSvgDuotone,
  fill: CubeSvgFill,
  light: CubeSvgLight,
  regular: CubeSvgRegular,
  thin: CubeSvgThin,
});

const DatabaseSvg = createIcon({
  bold: DatabaseSvgBold,
  duotone: DatabaseSvgDuotone,
  fill: DatabaseSvgFill,
  light: DatabaseSvgLight,
  regular: DatabaseSvgRegular,
  thin: DatabaseSvgThin,
});

const DotsThreeSvg = createIcon({
  bold: DotsThreeSvgBold,
  duotone: DotsThreeSvgDuotone,
  fill: DotsThreeSvgFill,
  light: DotsThreeSvgLight,
  regular: DotsThreeSvgRegular,
  thin: DotsThreeSvgThin,
});

const DownloadSimpleSvg = createIcon({
  bold: DownloadSimpleSvgBold,
  duotone: DownloadSimpleSvgDuotone,
  fill: DownloadSimpleSvgFill,
  light: DownloadSimpleSvgLight,
  regular: DownloadSimpleSvgRegular,
  thin: DownloadSimpleSvgThin,
});

const EnvelopeSimpleSvg = createIcon({
  bold: EnvelopeSimpleSvgBold,
  duotone: EnvelopeSimpleSvgDuotone,
  fill: EnvelopeSimpleSvgFill,
  light: EnvelopeSimpleSvgLight,
  regular: EnvelopeSimpleSvgRegular,
  thin: EnvelopeSimpleSvgThin,
});

const EyeSlashSvg = createIcon({
  bold: EyeSlashSvgBold,
  duotone: EyeSlashSvgDuotone,
  fill: EyeSlashSvgFill,
  light: EyeSlashSvgLight,
  regular: EyeSlashSvgRegular,
  thin: EyeSlashSvgThin,
});

const EyeSvg = createIcon({
  bold: EyeSvgBold,
  duotone: EyeSvgDuotone,
  fill: EyeSvgFill,
  light: EyeSvgLight,
  regular: EyeSvgRegular,
  thin: EyeSvgThin,
});

const FileMagnifyingGlassSvg = createIcon({
  bold: FileMagnifyingGlassSvgBold,
  duotone: FileMagnifyingGlassSvgDuotone,
  fill: FileMagnifyingGlassSvgFill,
  light: FileMagnifyingGlassSvgLight,
  regular: FileMagnifyingGlassSvgRegular,
  thin: FileMagnifyingGlassSvgThin,
});

const FileMdSvg = createIcon({
  bold: FileMdSvgBold,
  duotone: FileMdSvgDuotone,
  fill: FileMdSvgFill,
  light: FileMdSvgLight,
  regular: FileMdSvgRegular,
  thin: FileMdSvgThin,
});

const FileSvg = createIcon({
  bold: FileSvgBold,
  duotone: FileSvgDuotone,
  fill: FileSvgFill,
  light: FileSvgLight,
  regular: FileSvgRegular,
  thin: FileSvgThin,
});

const FolderOpenSvg = createIcon({
  bold: FolderOpenSvgBold,
  duotone: FolderOpenSvgDuotone,
  fill: FolderOpenSvgFill,
  light: FolderOpenSvgLight,
  regular: FolderOpenSvgRegular,
  thin: FolderOpenSvgThin,
});

const FolderSvg = createIcon({
  bold: FolderSvgBold,
  duotone: FolderSvgDuotone,
  fill: FolderSvgFill,
  light: FolderSvgLight,
  regular: FolderSvgRegular,
  thin: FolderSvgThin,
});

const FunnelSimpleSvg = createIcon({
  bold: FunnelSimpleSvgBold,
  duotone: FunnelSimpleSvgDuotone,
  fill: FunnelSimpleSvgFill,
  light: FunnelSimpleSvgLight,
  regular: FunnelSimpleSvgRegular,
  thin: FunnelSimpleSvgThin,
});

const GearSixSvg = createIcon({
  bold: GearSixSvgBold,
  duotone: GearSixSvgDuotone,
  fill: GearSixSvgFill,
  light: GearSixSvgLight,
  regular: GearSixSvgRegular,
  thin: GearSixSvgThin,
});

const GearSvg = createIcon({
  bold: GearSvgBold,
  duotone: GearSvgDuotone,
  fill: GearSvgFill,
  light: GearSvgLight,
  regular: GearSvgRegular,
  thin: GearSvgThin,
});

const GithubLogoSvg = createIcon({
  bold: GithubLogoSvgBold,
  duotone: GithubLogoSvgDuotone,
  fill: GithubLogoSvgFill,
  light: GithubLogoSvgLight,
  regular: GithubLogoSvgRegular,
  thin: GithubLogoSvgThin,
});

const GlobeSvg = createIcon({
  bold: GlobeSvgBold,
  duotone: GlobeSvgDuotone,
  fill: GlobeSvgFill,
  light: GlobeSvgLight,
  regular: GlobeSvgRegular,
  thin: GlobeSvgThin,
});

const HouseSvg = createIcon({
  bold: HouseSvgBold,
  duotone: HouseSvgDuotone,
  fill: HouseSvgFill,
  light: HouseSvgLight,
  regular: HouseSvgRegular,
  thin: HouseSvgThin,
});

const ImagesSvg = createIcon({
  bold: ImagesSvgBold,
  duotone: ImagesSvgDuotone,
  fill: ImagesSvgFill,
  light: ImagesSvgLight,
  regular: ImagesSvgRegular,
  thin: ImagesSvgThin,
});

const InfoSvg = createIcon({
  bold: InfoSvgBold,
  duotone: InfoSvgDuotone,
  fill: InfoSvgFill,
  light: InfoSvgLight,
  regular: InfoSvgRegular,
  thin: InfoSvgThin,
});

const LinkSimpleSvg = createIcon({
  bold: LinkSimpleSvgBold,
  duotone: LinkSimpleSvgDuotone,
  fill: LinkSimpleSvgFill,
  light: LinkSimpleSvgLight,
  regular: LinkSimpleSvgRegular,
  thin: LinkSimpleSvgThin,
});

const LinkSvg = createIcon({
  bold: LinkSvgBold,
  duotone: LinkSvgDuotone,
  fill: LinkSvgFill,
  light: LinkSvgLight,
  regular: LinkSvgRegular,
  thin: LinkSvgThin,
});

const LockSvg = createIcon({
  bold: LockSvgBold,
  duotone: LockSvgDuotone,
  fill: LockSvgFill,
  light: LockSvgLight,
  regular: LockSvgRegular,
  thin: LockSvgThin,
});

const MagnifyingGlassSvg = createIcon({
  bold: MagnifyingGlassSvgBold,
  duotone: MagnifyingGlassSvgDuotone,
  fill: MagnifyingGlassSvgFill,
  light: MagnifyingGlassSvgLight,
  regular: MagnifyingGlassSvgRegular,
  thin: MagnifyingGlassSvgThin,
});

const MinusSvg = createIcon({
  bold: MinusSvgBold,
  duotone: MinusSvgDuotone,
  fill: MinusSvgFill,
  light: MinusSvgLight,
  regular: MinusSvgRegular,
  thin: MinusSvgThin,
});

const MoonSvg = createIcon({
  bold: MoonSvgBold,
  duotone: MoonSvgDuotone,
  fill: MoonSvgFill,
  light: MoonSvgLight,
  regular: MoonSvgRegular,
  thin: MoonSvgThin,
});

const NewspaperSvg = createIcon({
  bold: NewspaperSvgBold,
  duotone: NewspaperSvgDuotone,
  fill: NewspaperSvgFill,
  light: NewspaperSvgLight,
  regular: NewspaperSvgRegular,
  thin: NewspaperSvgThin,
});

const OpenAiLogoSvg = createIcon({
  bold: OpenAiLogoSvgBold,
  duotone: OpenAiLogoSvgDuotone,
  fill: OpenAiLogoSvgFill,
  light: OpenAiLogoSvgLight,
  regular: OpenAiLogoSvgRegular,
  thin: OpenAiLogoSvgThin,
});

const PackageSvg = createIcon({
  bold: PackageSvgBold,
  duotone: PackageSvgDuotone,
  fill: PackageSvgFill,
  light: PackageSvgLight,
  regular: PackageSvgRegular,
  thin: PackageSvgThin,
});

const PaletteSvg = createIcon({
  bold: PaletteSvgBold,
  duotone: PaletteSvgDuotone,
  fill: PaletteSvgFill,
  light: PaletteSvgLight,
  regular: PaletteSvgRegular,
  thin: PaletteSvgThin,
});

const PencilRulerSvg = createIcon({
  bold: PencilRulerSvgBold,
  duotone: PencilRulerSvgDuotone,
  fill: PencilRulerSvgFill,
  light: PencilRulerSvgLight,
  regular: PencilRulerSvgRegular,
  thin: PencilRulerSvgThin,
});

const PencilSimpleSvg = createIcon({
  bold: PencilSimpleSvgBold,
  duotone: PencilSimpleSvgDuotone,
  fill: PencilSimpleSvgFill,
  light: PencilSimpleSvgLight,
  regular: PencilSimpleSvgRegular,
  thin: PencilSimpleSvgThin,
});

const PlugsConnectedSvg = createIcon({
  bold: PlugsConnectedSvgBold,
  duotone: PlugsConnectedSvgDuotone,
  fill: PlugsConnectedSvgFill,
  light: PlugsConnectedSvgLight,
  regular: PlugsConnectedSvgRegular,
  thin: PlugsConnectedSvgThin,
});

const PlusSvg = createIcon({
  bold: PlusSvgBold,
  duotone: PlusSvgDuotone,
  fill: PlusSvgFill,
  light: PlusSvgLight,
  regular: PlusSvgRegular,
  thin: PlusSvgThin,
});

const QuestionSvg = createIcon({
  bold: QuestionSvgBold,
  duotone: QuestionSvgDuotone,
  fill: QuestionSvgFill,
  light: QuestionSvgLight,
  regular: QuestionSvgRegular,
  thin: QuestionSvgThin,
});

const ShieldCheckSvg = createIcon({
  bold: ShieldCheckSvgBold,
  duotone: ShieldCheckSvgDuotone,
  fill: ShieldCheckSvgFill,
  light: ShieldCheckSvgLight,
  regular: ShieldCheckSvgRegular,
  thin: ShieldCheckSvgThin,
});

const SignOutSvg = createIcon({
  bold: SignOutSvgBold,
  duotone: SignOutSvgDuotone,
  fill: SignOutSvgFill,
  light: SignOutSvgLight,
  regular: SignOutSvgRegular,
  thin: SignOutSvgThin,
});

const SquaresFourSvg = createIcon({
  bold: SquaresFourSvgBold,
  duotone: SquaresFourSvgDuotone,
  fill: SquaresFourSvgFill,
  light: SquaresFourSvgLight,
  regular: SquaresFourSvgRegular,
  thin: SquaresFourSvgThin,
});

const StackSimpleSvg = createIcon({
  bold: StackSimpleSvgBold,
  duotone: StackSimpleSvgDuotone,
  fill: StackSimpleSvgFill,
  light: StackSimpleSvgLight,
  regular: StackSimpleSvgRegular,
  thin: StackSimpleSvgThin,
});

const StackSvg = createIcon({
  bold: StackSvgBold,
  duotone: StackSvgDuotone,
  fill: StackSvgFill,
  light: StackSvgLight,
  regular: StackSvgRegular,
  thin: StackSvgThin,
});

const SunSvg = createIcon({
  bold: SunSvgBold,
  duotone: SunSvgDuotone,
  fill: SunSvgFill,
  light: SunSvgLight,
  regular: SunSvgRegular,
  thin: SunSvgThin,
});

const TextBSvg = createIcon({
  bold: TextBSvgBold,
  duotone: TextBSvgDuotone,
  fill: TextBSvgFill,
  light: TextBSvgLight,
  regular: TextBSvgRegular,
  thin: TextBSvgThin,
});

const TextItalicSvg = createIcon({
  bold: TextItalicSvgBold,
  duotone: TextItalicSvgDuotone,
  fill: TextItalicSvgFill,
  light: TextItalicSvgLight,
  regular: TextItalicSvgRegular,
  thin: TextItalicSvgThin,
});

const TranslateSvg = createIcon({
  bold: TranslateSvgBold,
  duotone: TranslateSvgDuotone,
  fill: TranslateSvgFill,
  light: TranslateSvgLight,
  regular: TranslateSvgRegular,
  thin: TranslateSvgThin,
});

const TrashSvg = createIcon({
  bold: TrashSvgBold,
  duotone: TrashSvgDuotone,
  fill: TrashSvgFill,
  light: TrashSvgLight,
  regular: TrashSvgRegular,
  thin: TrashSvgThin,
});

const UploadSimpleSvg = createIcon({
  bold: UploadSimpleSvgBold,
  duotone: UploadSimpleSvgDuotone,
  fill: UploadSimpleSvgFill,
  light: UploadSimpleSvgLight,
  regular: UploadSimpleSvgRegular,
  thin: UploadSimpleSvgThin,
});

const UsersSvg = createIcon({
  bold: UsersSvgBold,
  duotone: UsersSvgDuotone,
  fill: UsersSvgFill,
  light: UsersSvgLight,
  regular: UsersSvgRegular,
  thin: UsersSvgThin,
});

const UserSvg = createIcon({
  bold: UserSvgBold,
  duotone: UserSvgDuotone,
  fill: UserSvgFill,
  light: UserSvgLight,
  regular: UserSvgRegular,
  thin: UserSvgThin,
});

const WarningCircleSvg = createIcon({
  bold: WarningCircleSvgBold,
  duotone: WarningCircleSvgDuotone,
  fill: WarningCircleSvgFill,
  light: WarningCircleSvgLight,
  regular: WarningCircleSvgRegular,
  thin: WarningCircleSvgThin,
});

const WarningOctagonSvg = createIcon({
  bold: WarningOctagonSvgBold,
  duotone: WarningOctagonSvgDuotone,
  fill: WarningOctagonSvgFill,
  light: WarningOctagonSvgLight,
  regular: WarningOctagonSvgRegular,
  thin: WarningOctagonSvgThin,
});

const WarningSvg = createIcon({
  bold: WarningSvgBold,
  duotone: WarningSvgDuotone,
  fill: WarningSvgFill,
  light: WarningSvgLight,
  regular: WarningSvgRegular,
  thin: WarningSvgThin,
});

const WrenchSvg = createIcon({
  bold: WrenchSvgBold,
  duotone: WrenchSvgDuotone,
  fill: WrenchSvgFill,
  light: WrenchSvgLight,
  regular: WrenchSvgRegular,
  thin: WrenchSvgThin,
});

const XCircleSvg = createIcon({
  bold: XCircleSvgBold,
  duotone: XCircleSvgDuotone,
  fill: XCircleSvgFill,
  light: XCircleSvgLight,
  regular: XCircleSvgRegular,
  thin: XCircleSvgThin,
});

const XSvg = createIcon({
  bold: XSvgBold,
  duotone: XSvgDuotone,
  fill: XSvgFill,
  light: XSvgLight,
  regular: XSvgRegular,
  thin: XSvgThin,
});

export const ArrowLeftIcon = ArrowLeftSvg;
export const ArrowRightIcon = ArrowRightSvg;
export const ArrowsLeftRightIcon = ArrowsLeftRightSvg;
export const ArrowSquareOutIcon = ArrowSquareOutSvg;
export const Article = ArticleSvg;
export const BellIcon = BellSvg;
export const BookOpenIcon = BookOpenSvg;
export const CalendarDotsIcon = CalendarDotsSvg;
export const CaretDownIcon = CaretDownSvg;
export const CaretUpDownIcon = CaretUpDownSvg;
export const ChartBarIcon = ChartBarSvg;
export const ChartLineIcon = ChartLineSvg;
export const ChartPieIcon = ChartPieSvg;
export const ChatCircle = ChatCircleSvg;
export const CheckCircleIcon = CheckCircleSvg;
export const CheckIcon = CheckSvg;
export const ClockCounterClockwiseIcon = ClockCounterClockwiseSvg;
export const CloudIcon = CloudSvg;
export const CloudSlash = CloudSlashSvg;
export const CodeIcon = CodeSvg;
export const CopyIcon = CopySvg;
export const CopySimpleIcon = CopySimpleSvg;
export const CreditCardIcon = CreditCardSvg;
export const CubeIcon = CubeSvg;
export const Database = DatabaseSvg;
export const DatabaseIcon = DatabaseSvg;
export const DotsThree = DotsThreeSvg;
export const DownloadSimpleIcon = DownloadSimpleSvg;
export const EnvelopeSimple = EnvelopeSimpleSvg;
export const Eye = EyeSvg;
export const EyeIcon = EyeSvg;
export const EyeSlashIcon = EyeSlashSvg;
export const FileIcon = FileSvg;
export const FileMagnifyingGlassIcon = FileMagnifyingGlassSvg;
export const FileMdIcon = FileMdSvg;
export const FolderIcon = FolderSvg;
export const FolderOpen = FolderOpenSvg;
export const FunnelSimpleIcon = FunnelSimpleSvg;
export const Gear = GearSvg;
export const GearIcon = GearSvg;
export const GearSixIcon = GearSixSvg;
export const GithubLogoIcon = GithubLogoSvg;
export const GlobeIcon = GlobeSvg;
export const House = HouseSvg;
export const HouseIcon = HouseSvg;
export const Images = ImagesSvg;
export const Info = InfoSvg;
export const InfoIcon = InfoSvg;
export const LinkIcon = LinkSvg;
export const LinkSimple = LinkSimpleSvg;
export const LinkSimpleIcon = LinkSimpleSvg;
export const LockIcon = LockSvg;
export const MagnifyingGlassIcon = MagnifyingGlassSvg;
export const Minus = MinusSvg;
export const Moon = MoonSvg;
export const MoonIcon = MoonSvg;
export const Newspaper = NewspaperSvg;
export const OpenAiLogo = OpenAiLogoSvg;
export const PackageIcon = PackageSvg;
export const Palette = PaletteSvg;
export const PencilRulerIcon = PencilRulerSvg;
export const PencilSimple = PencilSimpleSvg;
export const PencilSimpleIcon = PencilSimpleSvg;
export const PlugsConnected = PlugsConnectedSvg;
export const Plus = PlusSvg;
export const PlusIcon = PlusSvg;
export const QuestionIcon = QuestionSvg;
export const ShieldCheckIcon = ShieldCheckSvg;
export const SignOutIcon = SignOutSvg;
export const SquaresFourIcon = SquaresFourSvg;
export const StackIcon = StackSvg;
export const StackSimpleIcon = StackSimpleSvg;
export const Sun = SunSvg;
export const SunIcon = SunSvg;
export const TextBolderIcon = TextBSvg;
export const TextItalicIcon = TextItalicSvg;
export const TranslateIcon = TranslateSvg;
export const Trash = TrashSvg;
export const TrashIcon = TrashSvg;
export const UploadSimpleIcon = UploadSimpleSvg;
export const User = UserSvg;
export const UserIcon = UserSvg;
export const Users = UsersSvg;
export const UsersIcon = UsersSvg;
export const Warning = WarningSvg;
export const WarningCircle = WarningCircleSvg;
export const WarningIcon = WarningSvg;
export const WarningOctagonIcon = WarningOctagonSvg;
export const Wrench = WrenchSvg;
export const X = XSvg;
export const XCircleIcon = XCircleSvg;
export const XIcon = XSvg;
