export {
  Code,
  CodeBlock,
  codeVariants,
  KUMO_CODE_DEFAULT_VARIANTS,
  KUMO_CODE_STYLING,
  KUMO_CODE_VARIANTS,
  KUMO_CODEBLOCK_STYLING,
  type BundledLanguage,
  type CodeBlockProps,
  type CodeLang,
  type CodeProps,
  type KumoCodeLang,
  type KumoCodeVariantsProps,
} from "./code";
